### ISSUE TITLE
Run mypy job with Python 3.11 once it is supported

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#240] opened 2023-03-10 17:22 UTC
### Description

We should revert c3bfe6665e9d2420dfb2256c51e64ddc300f960a once mypy is sorted out (and if it's not mypy fault, then whatever we are doing wrong).

Maybe related to https://github.com/python/mypy/issues/12840, maybe we need to open a new issue over there?

**Comment by ricardoV94** [comment] 2023-03-11 21:13
I didn't save the run, but this was the error:

```
 [pytensor/link/c/exceptions.py]
 pytensor/link/c/exceptions.py:1: error: Module "setuptools._distutils.errors" has no attribute "CompileError"
```

**Comment by shreyas3156** [comment] 2023-03-12 19:12
I am facing this error even with Python 3.10 on my conda env. I retried creating the environment with Python 3.9 but the error still persists.

```
!!!!!!!!!
1 files unexpectedly failed.
pytensor/link/c/exceptions.py
These files did not fail before, so please check the above output for errors in {'pytensor/link/c/exceptions.py'} and fix them.
You can run `python scripts/run_mypy.py --verbose` to reproduce this test locally.


(pytensor-dev) sherryff@sherryff-HP-Notebook:~/MyProjects/pytensor$ python --version
Python 3.9.16
(pytensor-dev) sherryff@sherryff-HP-Notebook:~/MyProjects/pytensor$ which python
/home/sherryff/miniconda3/envs/pytensor-dev/bin/python

**Comment by ricardoV94** [comment] 2023-04-17 15:16
It also cropped up on a Python 3.10 job now, so it must be something else: https://github.com/pymc-devs/pytensor/actions/runs/4712555504/jobs/8357675677?pr=276

@michaelosthege do you have any ideas?

**Comment by maresb** [comment] 2023-04-17 17:56
Looks like a problem with `setuptools-types` which would be fixed by https://github.com/python/typeshed/pull/10057 and #277

**Comment by ricardoV94** [comment] 2023-04-17 18:03
Awesome 😎

**Comment by maresb** [comment] 2023-04-17 19:30
My typeshed PR has already been merged. A quick glance at their GH Actions suggests that there will soon be an automatic release to https://pypi.org/project/types-setuptools/#history. Once that's out, #277 should pass.

**Closed** 2023-04-18 07:19 UTC
Labels: maintenance, tests
